const fs = require("fs")
const Categorymodel = require("../models/Categorymodel")
const addCategory = async (req, res) => {
    try {
        var fname = "defaultpic.webp"
        if (req.file) {  //it shows that there is file in the request and admin wants to add new image
            fname = req.file.filename
        }
        const newrecord = Categorymodel({ catname: req.body.catname, picname: fname })
        const result = await newrecord.save()  //saving document to real collection
        if (result) {
            res.send({ code: 1 })
        }
        else {
            res.send({ code: 0 })
        }
    }
    catch (e) {
        console.log("ERROR:", e.message)
        res.send({ code: 0, error: e.message })
    }
}
const getAllCategories = async (req, res) => {
    try {
        const result = await Categorymodel.find()
        if (result.length == 0) {
            res.send({ code: 0 })
        }
        else {
            res.send({ code: 1, cdata: result })
        }
    }
    catch (e) {
        res.send({ code: 0 })
    }
}
const getAllCategoriesWithSubs = async (req, res) => {
    try {
        const result = await Categorymodel.find()
            .populate('subcategories')

        if (result.length === 0) {
            res.send({ code: 0 })
        }
        else {
            res.send({ code: 1, data: result })
        }
    }
    catch (e) {
        console.log(e)
        res.send({ code: 0 })
    }
}
const updateCategory = async (req, res) => {
    try {
        var imagename
        if (req.file) {  //it shows that there is file in the request and admin wants to change the image
            imagename = req.file.filename  //here we are saving new image name generated by multer into the variable
            if (req.body.oldpicname !== "defaultpic.webp") {
                const oldPath = `${req.file.destination}/${req.body.oldpicname}`

                if (fs.existsSync(oldPath)) {
                    fs.unlinkSync(oldPath)
                }  //it will delete the old file from folder
            }
        }
        else {
            imagename = req.body.oldpicname  //it shows that admin doesn't want to change the image
        }
        const result = await Categorymodel.updateOne({ _id: req.body.cid }, { catname: req.body.catname, picname: imagename })
        if (result.modifiedCount === 1) {
            res.send({ code: 1 })
        }
        else {
            res.send({ code: 0 })
        }
    }
    catch (e) {
        res.send({ code: 0 })
    }
}
const deleteCategory = async (req, res) => {
    try {
        const catdata = await Categorymodel.findOne({ _id: req.query.cid })

        if (!catdata) {
            res.send({ code: 0 })
            return
        }
        if (catdata.picname !== "defaultpic.webp") {   // delete image only if it is not default image
            const filepath = `public/uploads/${catdata.picname}`
            if (fs.existsSync(filepath))   //check if image exists
            {
                fs.unlinkSync(filepath)    //delete image from public/uploads
            }
        }
        const result = await Categorymodel.deleteOne({ _id: req.query.cid })

        if (result.deletedCount === 1) {
            res.send({ code: 1 })
        }
        else {
            res.send({ code: 0 })
        }
    }
    catch (e) {
        res.send({ code: 0 })
    }
}
module.exports = { addCategory, getAllCategories, getAllCategoriesWithSubs, updateCategory, deleteCategory}