const fs = require("fs")

const SubCategorymodel = require("../models/Subcategorymodel")
const Categorymodel = require("../models/Categorymodel")
 const addSubCategory = async (req, res) => {
    try {
        if (!req.body.cid || !req.body.scatname) {
            return res.send({ code: 0, msg: "Missing required fields" })
        }
        const categoryExists = await Categorymodel.findById(req.body.cid)

        if (!categoryExists) {
            return res.send({ code: 0, msg: "Invalid category" })
        }
        //it shows that there is file in the request and admin wants to add new image
        const fname = req.file ? req.file.filename : "defaultpic.webp"
        const newrecord = SubCategorymodel({ catid: req.body.cid, subcatname: req.body.scatname, picname: fname })
        const result = await newrecord.save()  //saving document to real collection
        if (result) {
            res.send({ code: 1 })
        }
        else {
            res.send({ code: 0 })
        }
    }
    catch (e) {
        res.send({ code: 0 })
    }
}
const getAllSubCategories = async (req, res) => {
    try {
        const result = await SubCategorymodel.find()
        if (result.length == 0) {
            res.send({ code: 0 })
        }
        else {
            res.send({ code: 1, cdata: result })
        }
    }
    catch (e) {
        res.send({ code: 0 })
    }
}
const getSubCatByCategory = async (req, res) => {
    try {
        const result = await SubCategorymodel.find({ catid: req.query.cid }).populate("catid")
        if (result.length == 0) {
            res.send({code: 1, scdata: result })
        }
        else {
            res.send({ code: 1, scdata: result })
        }
    }
    catch (e) {
        res.send({ code: 0 })
    }
}
const updateSubCategory =  async (req, res) => {
    try {
        var imagename
        if (req.file) {  //it shows that there is file in the request and admin wants to change the image
            imagename = req.file.filename  //here we are saving new image name generated by multer into the variable
            if (req.body.oldpicname !== "defaultpic.webp") {
                const oldPath = `${req.file.destination}/${req.body.oldpicname}`

                if (fs.existsSync(oldPath)) {
                    fs.unlinkSync(oldPath)
                }  //it will delete the old file from folder
            }
        }
        else {
            imagename = req.body.oldpicname  //it shows that admin doesn't want to change the image
        }
        const result = await SubCategorymodel.updateOne({ _id: req.body.scid }, { subcatname: req.body.scatname, picname: imagename })
        if (result.modifiedCount === 1) {
            res.send({ code: 1 })
        }
        else {
            res.send({ code: 0 })
        }
    }
    catch (e) {
        res.send({ code: 0 })
    }
}
const deleteSubCategory =  async (req, res) => {
    try {
        const subcatdata = await SubCategorymodel.findOne({ _id: req.query.scid })

        if (!subcatdata) {
            res.send({ code: 0 })
            return
        }
        // delete image if not default
        if (subcatdata.picname !== "defaultpic.webp") {
            const filepath = `public/uploads/${subcatdata.picname}`
            if (fs.existsSync(filepath)) {
                fs.unlinkSync(filepath)
            }
        }
        const result = await SubCategorymodel.deleteOne({ _id: req.query.scid })
        if (result.deletedCount === 1) {
            res.send({ code: 1 })
        }
        else {
            res.send({ code: 0 })
        }
    }
    catch (e) {
        res.send({ code: 0 })
    }
}
module.exports = { addSubCategory, getAllSubCategories, getSubCatByCategory, updateSubCategory, deleteSubCategory}